### ISSUE TITLE
for alidns-webhook error

### ISSUE THREAD

**Issue by Hello-Linux** [pragkent/alidns-webhook#4]
the error is https://github.com/jetstack/cert-manager/issues/2680

**Comment by pragkent** [comment]
Could you please paste logs from the alidns-webhook pod?
And have you changed anything of bundle.yaml?

**Comment by Hello-Linux** [comment]
Yes, I chaned your bundle.yaml, beause the apiversion "certmanager.k8s.io/v1alpha1" is old
![2020-03-11 16-00-28 的屏幕截图](https://user-images.githubusercontent.com/17851645/76395084-892cd780-63b1-11ea-8961-50834f6b9e9d.png)
then I changed the apiversion to "cert-manager.io/v1alpha2"

**Comment by Hello-Linux** [comment]
@pragkent  and the alidns-pod logs is
![2020-03-11 17-03-25 的屏幕截图](https://user-images.githubusercontent.com/17851645/76399856-53d8b780-63ba-11ea-8eb7-27f88860aa02.png)

**Comment by Hello-Linux** [comment]
@pragkent  the pod error is "I0311 09:06:21.887651       1 log.go:172] http: TLS handshake error from 192.168.40.115:44962: remote error: tls: bad certificate"  Why?

**Comment by pragkent** [comment]
Please check your `bundle.yaml`, I think you also need to change annotations of APIService from
```
certmanager.k8s.io/inject-ca-from: "cert-manager/alidns-webhook-webhook-tls
```
to

```
cert-manager.io/inject-ca-from: "cert-manager/alidns-webhook-webhook-tls
```

**Comment by Hello-Linux** [comment]
@pragkent  After changing this file, I still have this error
`I0312 07:27:54.904753       1 log.go:172] http: TLS handshake error from 192.168.40.115:57886: remote error: tls: bad certificate
I0312 07:28:20.022454       1 log.go:172] http: TLS handshake error from 192.168.40.115:57950: remote error: tls: bad certificate
I0312 07:28:20.105644       1 log.go:172] http: TLS handshake error from 192.168.40.115:57952: remote error: tls: bad certificate
I0312 07:28:22.278387       1 log.go:172] http: TLS handshake error from 192.168.40.115:57966: remote error: tls: bad certificate
`
![2020-03-12 15-26-26 的屏幕截图](https://user-images.githubusercontent.com/17851645/76497466-fdc94a00-6475-11ea-8c84-d31257d18bbe.png)

**Comment by Hello-Linux** [comment]
@pragkent  Have you tested this feature yourself recently?

**Comment by pragkent** [comment]
Have not. I only tested on cert-manager 0.8.1.
What's your cert-manager version?

**Comment by Hello-Linux** [comment]
@pragkent   My cert-manager is 0.13,Can you test it on the new version? I think your warehouse is the official webhook

**Comment by pragkent** [comment]
@Hello-Linux ok, I'll have a test. I'll get back to you later.

**Comment by yinfxs** [comment]
bad certificate +1

**Comment by pragkent** [comment]
@Hello-Linux it's my fault. 
The  DNS names used in webhook-tls is wrong, which caused tls handshake error.

And according to the current RBAC settings, the webhook pod need access right of `alidns-secret`,
so it would be easier to use ClusterIssuer instead of Issuer, and create `alidns-secret` in cert-manager namespace.

You can find detail here:
[fix](https://github.com/pragkent/alidns-webhook/commit/71bdc60c03d51429cb061f98ba1666c57c9ab78d)

**Comment by pragkent** [comment]
@yinfxs Please try master branch.

**Comment by Hello-Linux** [comment]
@pragkent  No problem now?

**Comment by Hello-Linux** [comment]
@pragkent  I just tested it and it still doesn't work
![2020-03-13 17-44-49 的屏幕截图](https://user-images.githubusercontent.com/17851645/76609606-9cc37400-6552-11ea-8265-9d1a35b1e579.png)
![2020-03-13 17-45-24 的屏幕截图](https://user-images.githubusercontent.com/17851645/76609613-a0ef9180-6552-11ea-9657-4ac232f4cf3a.png)

**Comment by pragkent** [comment]
I tested this on my machine, it works fine.
Could you please paste your bundle.yaml, cert and issuer here?

**Comment by pragkent** [comment]
And the tls certificate contents:

``` kubectl describe cert -n cert-manager alidns-webhook-webhook-tls```

**Comment by Hello-Linux** [comment]
@pragkent 
![2020-03-13 21-29-49 的屏幕截图](https://user-images.githubusercontent.com/17851645/76625265-d22b8a00-6571-11ea-8e7e-7cd469a5429a.png)

**Comment by pragkent** [comment]
Hmm... I just tested your bundle.yaml  on a brand new gke cluster, and it works.

```bash
pragkent@cloudshell:~$ kubectl logs -n cert-manager alidns-webhook-6d9b499464-gsjmq
I0314 02:08:11.486549       1 secure_serving.go:116] Serving securely on [::]:443
I0314 02:11:57.312131       1 solver.go:47] Presenting txt record: _acme-challenge.jira.nihao2.com. com.
```
The webhook pod is serving https traffic using tls cert saved in `cert-manager/alidns-webhook-webhook-tls`.

Maybe you can try to delete the webhook resources and apply them again?
```bash
kubectl delete -f bundle.yaml
# also delete tls secrets generated by webhook certificates.
kubectl delete secret -n cert-manager alidns-webhook-webhook-tls alidns-webhook-ca
```

**Comment by Hello-Linux** [comment]
@pragkent  Succeeded! Just delete and re-create it.

**Comment by pragkent** [comment]
Cool, then I'll close the issue for now.

**Comment by Hello-Linux** [comment]
@pragkent  ok

**Comment by petergithub** [comment]
> @pragkent and the alidns-pod logs is ![2020-03-11 17-03-25 的屏幕截图](https://user-images.githubusercontent.com/17851645/76399856-53d8b780-63ba-11ea-8eb7-27f88860aa02.png)

Got the same issue. 
Just delete the pod `alidns-webhook-`, after the new pod is created. The error is gone and `certificate` is in a READY status.
